#!/bin/bash

gsettings set org.mate.interface icon-theme Arc
gsettings set org.mate.interface gtk-theme Arc-Darker
gsettings set org.gnome.desktop.interface icon-theme Arc
gsettings set org.gnome.desktop.interface gtk-theme Arc-Darker
