colors = '''
client.focused          #d46a84 #d46a84 #ffffff #f55050   #d46a84
client.focused_inactive #c799a5 #c799a5 #3b2c33 #292d2e   #c799a5
client.unfocused        #f0dde6 #f0dde6 #3b2c33 #484e50   #f0dde6
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

client.background       #ffffff
'''

background = '~/med/pic/db/Wallpapers/hld/city.png'
